package com.unsocial.unsocial.controller;

import com.unsocial.unsocial.dto.*;
import com.unsocial.unsocial.service.ChatbotService;
import com.unsocial.unsocial.service.KnowledgeBaseService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/chatbot")
@RequiredArgsConstructor
public class ChatbotController {

    private final ChatbotService chatbotService;
    private final KnowledgeBaseService knowledgeBaseService;

    /**
     * POST /api/chatbot/ask
     * Ask the AI Safety Assistant a question. Answers are grounded (RAG)
     * in UnSocial's own safety + app-help knowledge base, generated by a
     * local Ollama model.
     */
    @PostMapping("/ask")
    public ResponseEntity<ApiResponse<ChatAnswerResponse>> ask(
            @Valid @RequestBody ChatRequest request
    ) {
        ChatAnswerResponse response = chatbotService.ask(request.getMessage());
        return ResponseEntity.ok(ApiResponse.success("Response generated", response));
    }

    /**
     * GET /api/chatbot/history
     * Full conversation history for the logged-in user, oldest first.
     */
    @GetMapping("/history")
    public ResponseEntity<ApiResponse<List<ChatMessageResponse>>> getHistory() {
        return ResponseEntity.ok(ApiResponse.success("Chat history retrieved", chatbotService.getHistory()));
    }

    /**
     * DELETE /api/chatbot/history
     * Clears the logged-in user's conversation history.
     */
    @DeleteMapping("/history")
    public ResponseEntity<ApiResponse<Void>> clearHistory() {chatbotService.clearHistory();
        return ResponseEntity.ok(ApiResponse.success("Chat history cleared", null));
    }

    /**
     * POST /api/chatbot/admin/reindex
     * Rebuilds the knowledge base from the markdown files in
     * resources/knowledge-base/. Call this after editing that content.
     * Requires ADMIN role (see UPDATE_NOTES for how to promote a user)
     * and a running Ollama instance.
     */
    @PostMapping("/admin/reindex")
    @PreAuthorize("hasRole('ADMIN')")
    public ResponseEntity<ApiResponse<ReindexResponse>> reindex() {
        long start = System.currentTimeMillis();
        int count = knowledgeBaseService.reindex();
        ReindexResponse response = ReindexResponse.builder()
                .chunksIndexed(count)
                .durationMs(System.currentTimeMillis() - start)
                .build();
        return ResponseEntity.ok(ApiResponse.success("Knowledge base re-indexed", response));
    }
}
